version: '2.1'

services: 
  tdbs-mysql:
    image: tdbs-mysql-image
    container_name: "tdbs-mysql"
    restart: always
    #ports:
    #  - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Root@tss
      - MYSQL_DATABASE=tdbs
      - MYSQL_USER=tss
      - MYSQL_PASSWORD=Root@tss
      
  spring-boot-tdbs:
    image: tss/tdbs
    container_name: "tdbs-api"
    restart: always
    links:
      - tdbs-mysql
    depends_on:
      - tdbs-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=tdbs-mysql
      - DATABASE_USER=tdbs
      - DATABASE_PASSWORD=Root@tss
      - DATABASE_NAME=tdbs
      - DATABASE_PORT=3306